export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
alias cl="clear"
alias dOne="cd ~/glib/doomstuff; chocolate-doom -iwad DOOM1.WAD"
alias cdg="cd ~/glib"
alias clock="cl;tty-clock -c"
alias mkpkg="makepkg -sirc"
alias srcdatshi="source ~/.zshrc"
alias editrc="nvim ~/.zshrc"
alias shit="shutdown -h 0"
alias reshit="shutdown -r 0"
alias cdcp="cd ~/code/gnatAttack/src"
alias cdconf="cd ~/.config"
alias cle="clear;neofetch"
alias clc="clear;make"
alias print_colors="sh ~/scripts/print_colors.sh"
alias quit="exit"
alias gc="git clone"
alias gac="git add .; git commit -m"
alias gp="git push"
alias cdsp="cd ~/code/taskManager"
source "$HOME/.zsh/spaceship/spaceship.zsh"
cle
